# Generated by Django 2.0.9 on 2019-04-08 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=128, verbose_name='Ödeme Numarası')),
                ('transaction_time', models.DateTimeField(auto_now_add=True, verbose_name='Ödeme Tarihi')),
                ('transaction_total_amount', models.FloatField(verbose_name='Toplam Ödeme')),
                ('status', models.CharField(choices=[('DISAPPROVED', 'Onaylanmadı'), ('APPROVED', 'Onaylandı'), ('REFUNDED', 'Iade Edildi')], default='DISAPPROVED', max_length=128, verbose_name='Durum')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL, verbose_name='Misafir')),
                ('card', models.ManyToManyField(related_name='card', to='djangoecommerce_app.Card', verbose_name='Sepetteki Ürünler')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoecommerce_app.Coupon', verbose_name='Kupon')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_owner', to=settings.AUTH_USER_MODEL, verbose_name='Sahibi')),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
                'ordering': ('-transaction_time',),
            },
        ),
    ]
