# Generated by Django 2.0.9 on 2019-04-08 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoecommerce_app', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProductComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Ürün Yorumu')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_owner', to=settings.AUTH_USER_MODEL, verbose_name='Yorum Yapan Kişi')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='djangoecommerce_app.Card', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün Yorumu',
                'verbose_name_plural': 'Ürün Yorumları',
            },
        ),
        migrations.CreateModel(
            name='OrderProductStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('EXPECTEDSHIPPED', 'Kargoya verilmesi bekleniyor.'), ('INCARGO', 'Ürününüz kargoda.'), ('DONE', 'Teslim edildi.')], default='EXPECTEDSHIPPED', max_length=15, verbose_name='Durum')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='djangoecommerce_app.Card', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Kargo Durumu',
                'verbose_name_plural': 'Kargo Durumları',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL, verbose_name='Satın Alan'),
        ),
    ]
