# Generated by Django 2.0.9 on 2019-04-08 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoecommerce_app', '0003_auto_20190408_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstar',
            name='star',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Yıldız'),
            preserve_default=False,
        ),
    ]
