# Generated by Django 2.0.9 on 2019-04-08 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoecommerce_app', '0004_productstar_star'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productstar',
            options={'ordering': ('-pk',), 'verbose_name': 'Ürün Yıldızı', 'verbose_name_plural': 'Ürün Yıldızları'},
        ),
    ]
