# Generated by Django 2.0.9 on 2019-04-08 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoecommerce_app', '0005_auto_20190408_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoecommerce_app.Product', verbose_name='Ürün'),
        ),
        migrations.AlterField(
            model_name='productstar',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoecommerce_app.Product', verbose_name='Ürün'),
        ),
    ]
