# Generated by Django 2.0.9 on 2019-04-08 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoecommerce_app', '0007_auto_20190408_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyfeature',
            options={'ordering': ('-id',), 'verbose_name': 'Şirket Özelliği', 'verbose_name_plural': 'Şirket Özellikleri'},
        ),
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_owner', to='djangoecommerce_app.Company', verbose_name='Ürün Sahip Firma'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoecommerce_app.ProductCategory', verbose_name='Ürün Kategorisi'),
        ),
    ]
