# Generated by Django 2.1.8 on 2019-04-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoecommerce_app', '0013_auto_20190419_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=50, verbose_name='Mail')),
                ('subject', models.CharField(max_length=200, verbose_name='Başlık')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Mesaj')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Oluşum Tarihi')),
            ],
            options={
                'verbose_name': 'İletişim',
                'verbose_name_plural': 'İletişimler',
            },
        ),
    ]
