# Generated by Django 2.0.9 on 2019-04-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoecommerce_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Blog Thumbnail'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='category_tubnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Kategori Tubnailı'),
        ),
    ]
