# Generated by Django 2.0.9 on 2019-04-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoecommerce_blog', '0002_auto_20190415_1834'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/blog/thumbnail/', verbose_name='Blog Thumbnail'),
        ),
    ]
