# Generated by Django 2.1.8 on 2019-04-18 15:43

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoecommerce_blog', '0003_auto_20190416_0053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-created_date',), 'verbose_name': 'Blog', 'verbose_name_plural': 'Bloglar'},
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
